version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db-go-tweets
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: superSecret
      MYSQL_DATABASE: go_tweets
    volumes:
      - /Users/devanshi/Desktop/code/practice/db-go-tweets:/var/lib/mysql



# docker compose up -d
# docker ps
